version: '3'

services:

  mongodb:
#    environment:
#      MONGO_INITDB_DATABASE: mydatabase
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password
    hostname: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data-mongodb:/data/db